---
- hosts: trackdirect
  remote_user: root
  tasks:
    - name: Copy config file
      copy:
        src: trackdirect
        dest: /opt/
        owner: root
        group: root
        mode: '0644'

    - name: Run `docker-compose down`
      community.docker.docker_compose_v2:
        project_src: /opt/trackdirect
        state: absent

    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /opt/trackdirect
        pull: always

    - name: Add cleanup job
      ansible.builtin.cron:
        name: "trackdirect cleanup"
        minute: "0"
        hour: "0"
        job: "docker-compose -f /opt/trackdirect/docker-compose.yml exec websocket /root/trackdirect/server/scripts/remover.sh trackdirect.ini"
