name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]


env:
  TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
  TF_VAR_HCLOUD_DNS_TOKEN: ${{ secrets.TF_VAR_HCLOUD_DNS_TOKEN }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  servers:
    name: Setup servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Init
        run: cd 01_hetzner && terraform init
      - name: Terraform Plan
        run: cd 01_hetzner && terraform plan
      - name: Terraform Apply
        run: cd 01_hetzner && terraform apply -auto-approve

  sw_setup:
    needs: servers
    name: Install all the needed Software and setup Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Init
        run: cd 01_hetzner && terraform init
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Accept ssh keys
        run: cd 01_hetzner && ./terraform-swarm-inventory.py --accept
      - name: Install Docker
        run: cd 02_sw_setup && ansible-playbook -i ../01_hetzner/terraform-swarm-inventory.py cluster_setup.yml

  stacks:
    needs: sw_setup
    name: Deploy Docker stacks to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Init
        run: cd 01_hetzner && terraform init
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Accept ssh keys
        run: cd 01_hetzner && ./terraform-swarm-inventory.py --accept
      - name: Deploy trackdirect
        run: cd 03_stacks && ansible-playbook -i ../01_hetzner/terraform-swarm-inventory.py deploy_trackdirect.yml
